version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '01:00'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /admin-ui
    schedule:
      interval: weekly
      day: monday
      time: '01:10'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    groups:
      admin-ui-npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /public-web
    schedule:
      interval: weekly
      day: monday
      time: '01:20'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    groups:
      public-web-npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '01:30'
      timezone: Asia/Shanghai
