const EXACT_MESSAGES: Record<string, string> = {
  'Invalid or expired access token': '登录已过期，请重新登录',
  'Internal Server Error': '服务器开小差了，请稍后再试',
  'Organization not initialized': '机构信息未初始化',
  'Account not found': '账号不存在',
  'Guardian not found': '家长不存在',
  'Student not found': '学员不存在',
  'Teacher not found': '老师不存在',
  'Institution not found': '机构不存在',
  'Campus not found': '校区不存在',
  'Classroom not found': '教室不存在',
  'Class not found': '班级不存在',
  'Class session not found': '课次不存在',
  'Course not found': '课程不存在',
  'Course series not found': '课程系列不存在',
  'Course package not found': '课时包不存在',
  'Course contract not found': '正式课程档案不存在',
  'Content not found': '内容不存在',
  'Channel not found': '渠道不存在',
  'Campaign not found': '活动不存在',
  'Campaign is not active': '活动未启用',
  'Lead not found': '线索不存在',
  'Enrollment not found': '入班记录不存在',
  'Notification not found': '通知不存在',
  'Homework check-in not found': '作业打卡不存在',
  'Student work not found': '学员作品不存在',
  'Teacher profile is not linked': '当前账号未关联老师档案',
  'Trial session not found': '试听场次不存在',
  'Trial session is not open': '该试听场次暂未开放',
  'Trial session has already started': '该试听场次已开始，不能预约',
  'Trial session is full': '该试听场次名额已满',
  'Lead has no trial booking': '该线索没有试听预约',
  'Selected campus is not available': '所选校区暂不可用',
  'Selected campus is not available for this course': '所选校区暂不支持该课程',
  'Selected teacher is not available': '所选老师暂不可用',
  'Selected teacher is not available for this course': '所选老师暂不支持该课程',
  'Seat reservation not found': '试听席位不存在',
  'Only reserved seats can be operated': '只能操作已保留的试听席位',
  'Seat reservation fee is not paid': '试听席位保留费未支付',
  'Only pending seat reservations can be rescheduled': '只有待确认的试听预约可以改期',
  'Seat reservation can only be rescheduled once': '试听预约只能改期一次',
  'Seat reservation has no trial session': '该试听预约没有关联场次',
  'Please choose another trial session': '请选择其他试听场次',
  'Seat reservation can no longer be rescheduled': '该试听预约已不能改期',
  'Checked-in seat reservations cannot be marked no-show': '已签到的试听预约不能标记未到',
  'Checked-in seat reservations cannot be cancelled': '已签到的试听预约不能取消',
  'Target trial session not found': '目标试听场次不存在',
  'Target trial session is not open': '目标试听场次暂未开放',
  'Target trial session has already started': '目标试听场次已开始',
  'Target trial session is full': '目标试听场次名额已满',
  'Seat reservation can only be rescheduled within the same course': '只能改期到同一课程的试听场次',
  'Seat reservation fee is not enabled': '该试听场次未开启席位保留费',
  'This trial session has no reservation fee': '该试听场次未设置席位保留费',
  'Order not found': '订单不存在',
  'Refund request not found': '退款申请不存在',
  'Only paid orders can be refunded': '只有已支付订单可以退款',
  'Order has no live payment provider to sync': '该订单没有可同步的线上支付渠道',
  'Class capacity reached': '班级人数已满',
  'Classroom or teacher time conflict': '教室或老师时间冲突',
  'Class session is cancelled': '课次已取消',
  'Student is not enrolled in this class session': '该学员未报名本次课',
  'Gift course not found': '赠课课程不存在',
  'Gift class not found': '赠课班级不存在',
  'Settlement batch not found': '结算批次不存在',
  'Only paid reserved seats can be converted': '只有已支付并保留的试听席位可转正式',
  'Only checked-in seat reservations can be converted': '只有已签到的试听席位可转正式',
  'Payment provider did not return a QR code': '支付渠道未返回付款二维码',
  'Mock payment is disabled in production': '生产环境不支持模拟支付',
  'WECHAT_PAY_APP_ID is not configured': '微信支付 AppID 未配置',
  'WECHAT_PAY_KEY is not configured': '微信支付密钥未配置',
  'WeChat Pay is not configured': '微信支付未配置',
  'Alipay is not configured': '支付宝支付未配置',
  'WeChat Pay only supports CNY': '微信支付仅支持人民币',
  'Alipay only supports CNY': '支付宝仅支持人民币',
  'Missing WeChat Mini Program openid': '缺少小程序用户标识，请重新登录后再试',
  'Empty WeChat Pay XML payload': '微信支付回调内容为空',
  'Failed to parse WeChat Pay XML payload': '微信支付回调解析失败',
  'Amount must be stored as integer cents': '金额数据异常，请联系管理员',
  'Missing WeChat Pay signature': '微信支付回调缺少签名',
  'Invalid WeChat Pay callback signature': '微信支付回调签名无效',
  'Missing WeChat Pay callback body': '微信支付回调内容为空',
  'Missing WeChat Pay payment fields': '微信支付回调参数不完整',
  'Missing WeChat Pay query payment fields': '微信支付查询参数不完整',
  'Invalid WeChat Pay total_fee': '微信支付金额异常',
  'WeChat Pay app id mismatch': '微信支付 AppID 不匹配',
  'WeChat Pay merchant id mismatch': '微信支付商户号不匹配',
  'Missing Alipay callback body': '支付宝回调内容为空',
  'Invalid Alipay callback signature': '支付宝回调签名无效',
  'Missing Alipay payment fields': '支付宝回调参数不完整',
  'Missing Alipay query payment fields': '支付宝查询参数不完整',
  'Alipay app id mismatch': '支付宝 AppID 不匹配',
};

const PATTERN_MESSAGES: Array<[RegExp, string]> = [
  [/^Request failed: \d+$/i, '请求失败，请稍后再试'],
  [/^Order not found:/i, '订单不存在'],
  [/^Order provider mismatch/i, '订单支付渠道不匹配'],
  [/^Order amount mismatch/i, '订单金额不匹配'],
  [/^Order currency mismatch/i, '订单币种不匹配'],
  [/^Order is not payable from status:/i, '当前订单状态不可支付'],
  [/^Unknown payment provider:/i, '未知支付渠道'],
  [/^Unsupported payment provider:/i, '不支持的支付渠道'],
  [/ does not support Mini Program payment$/i, '该支付渠道不支持小程序支付'],
  [/^Invalid amount value:/i, '金额格式不正确'],
  [/^Failed to read .* from /i, '读取配置失败，请检查系统设置'],
  [/^WeChat Pay create order failed:/i, '创建微信支付订单失败，请稍后再试'],
  [/^WeChat Pay query order failed:/i, '查询微信支付订单失败，请稍后再试'],
  [/^Alipay create order failed:/i, '创建支付宝订单失败，请稍后再试'],
  [/^Alipay query order failed:/i, '查询支付宝订单失败，请稍后再试'],
  [/ is not configured$/i, '支付配置未完成，请联系管理员'],
  [/^request:fail/i, '网络请求失败，请检查网络'],
];

function hasChinese(value: string): boolean {
  return /[\u3400-\u9fff]/.test(value);
}

export function toUserFacingMessage(message: unknown, fallback = '操作失败'): string {
  if (typeof message !== 'string') return fallback;
  const normalized = message.trim();
  if (!normalized) return fallback;
  if (EXACT_MESSAGES[normalized]) return EXACT_MESSAGES[normalized];
  const pattern = PATTERN_MESSAGES.find(([pattern]) => pattern.test(normalized));
  if (pattern) return pattern[1];
  return hasChinese(normalized) ? normalized : fallback;
}
